name: smart_notice_board_admin
description: A Flutter admin panel for managing Smart Notice Board content.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.19.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.3.2
  firebase_storage: ^10.3.0
  provider: ^6.0.3
  file_picker: ^5.5.0

flutter:
  uses-material-design: true
